language: java
sudo: false

jdk:
  - oraclejdk8

script:
  - ./gradlew --info check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email: false
